### ISSUE TITLE
Direct video does not output

### ISSUE THREAD

**Issue by soulctcher** [MiSTer-devel/Arcade-VBall_MiSTer#1]
The core does not output direct video.  Results on my Wells Gardner D9200 are a black screen.  I can confirm the core is running, as there is audio.

**Comment by pcornier** [comment]
I can only test VGA/CRT from my side. Can you check if the new version (Arcade-VBall_20210621.rbf) fixes direct video? Thank you.

**Comment by soulctcher** [comment]
I saw that there was an update and the core now does display on my D9200 CRT as well.  Thanks for the work on this game, it's one of the ones I've enjoyed in years past.
